name: FTP Deploy

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: mattbailey/ftp-deploy-action@v1.0.0
        with:
          ftp-server: ftp-sepaehs.alwaysdata.net
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Specify your local directory (default is root)
          server-dir: /www/  # Specify the server directory to deploy to
