name: FTP Deploy

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: lukaszgolebiewski/ftp-action@v1
        with:
          host: ftp-sepaehs.alwaysdata.net
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./
          remoteDir: /www/
