name: FTP Deploy

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: sebastianpopp/git-ftp-action@v4
        with:
          url: ftp://ftp-sepaehs.alwaysdata.net
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Change if you have specific folders to deploy
